name: "React CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Lint
        working-directory: client
        run: npm run lint

      - name: Run tests
        working-directory: client
        run: npm test -- --watchAll=false

      - name: Build
        working-directory: client
        run: npm run build
